on:
  pull_request:
    branches:
    - main
jobs:
  my_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        working-directory: /home/runner/work/Demo-Project/package.json
        run: npm install
      - name: Build the project
        run: node ace build
